layout_spectrum: 0.046694286688240154
typography_spectrum: 0.3974702722647476
color:
  lightness: 0.4748695946375074
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  saturation: 0.6696543717755946
  brandStrength: 0.49985948071529224
  rhythmicContrast: 0.9135564389637681
name: MVS Design
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
