collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6469534
  brandStrength: 0
  lightness: 0.7437276
  brandColors:
    - '#FBFAFB'
    - '#030203'
    - '#666F76'
    - '#03ABA3'
    - '#028842'
  rhythmicContrast: 0.2508961
typography_spectrum: 1
layout_spectrum: 0.8835126
name: MVS Design
